services:
  LoveCardsPHP:
    image: ghcr.io/jellyfish-p/lovecardsv2docker
    container_name: LoveCardsPHP
    volumes:
      - ./LoveCardsV2/storage:/var/www/html/public/storage
      # - ./LoveCardsV2/theme:/var/www/html/public/theme
    ports:
      - '${LOVECARDS_PORT}:80'
    depends_on:
      - LoveCardsMySQL

  LoveCardsMySQL:
    image: mysql:8.0
    container_name: LoveCardsMySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./LoveCardsMySQL:/var/lib/mysql

