name: LoveCardsV2Docker Deploy
run-name: ${{ github.actor }} deployed LoveCardsV2Docker
on: [push]
jobs:
  test_deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[test]')"
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t lovecardsv2 .